[package]
name = "fc-consensus"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Frontier consensus for substrate"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository = "https://github.com/paritytech/frontier/"

[dependencies]
async-trait = "0.1"
thiserror = "1.0"

sp-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-02" }
sp-block-builder = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-02" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-02" }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-02" }
sp-runtime = { version = "4.1.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-02" }

sc-client-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-02" }
sc-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-02" }

fp-consensus = { version = "2.0.0-dev", path = "../../primitives/consensus" }
fp-rpc = { version = "3.0.0-dev", path = "../../primitives/rpc" }
fc-db = { version = "2.0.0-dev", path = "../db" }
